services: 
  app: 
    image:  ${DOCKER_IMAGE}:${DOCKER_TAG}
    ports: 
      - "3000:3000" 
    environment: 
      - MYSQL_HOST=db 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
      - MYSQL_DB=todos 
    depends_on: 
      db:
        condition: service_healthy
  db: 
    image: mysql:8.0 
    environment: 
      - MYSQL_ROOT_PASSWORD=root_password 
      - MYSQL_DATABASE=todos 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p${MYSQL_PASSWORD}" ]
      timeout: 20s
      retries: 10
    volumes: 
      - db-data:/var/lib/mysql 
volumes: 
  db-data:
